services:
  backend:
    build: backend
    restart: always
    depends_on:
      db:
        condition: service_started
        restart: true
    ports:
      - 8080:8080
    env_file: "configs/backend.env"
    networks:
      - gym_network
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gym_network
    env_file: "configs/db.env"
    expose:
      - 5432
volumes:
  db-data:
networks:
  gym_network: